apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: junes
  namespace: compiler
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: area
            image: busybox
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh", "-ec", "sleep 40"]
            #image: perl
            #command: ["perl", "-Mbignum=bpi", "print bpi(2000)"]
          restartPolicy: OnFailure

