apiVersion: apps/v1
kind: Deployment

metadata:
  name: deploy
  namespace: compiler 
  labels:
    app: test
spec: 
  replicas: 2
  selector: 
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test      
    spec:
      containers:
      - name: hello
        image: bitbull/webserver
        ports:
        - containerPort: 80

