apiVersion: batch/v1
kind: Job
metadata:
  name: area21
  namespace: compiler
spec:
  activeDeadlineSeconds: 3
  backoffLimit: 2
  completions: 3
  parallelism: 2
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: OnFailure
  
