apiVersion: v1
kind: Pod
metadata:
  name: config-file
  namespace: compiler
  labels:
    name: test
spec:
  containers:
  - name: test
    image: bitbull/webserver
    ports:
    - containerPort: 80
    env:
    - name: world
      valueFrom:
        configMapKeyRef:
           name: config
           key: Description
    volumeMounts:
     - name: test-config
       mountPath: "/etc/xml"
       readOnly: true
          
  volumes:
    - name: test-config
      configMap:
        name: config
