apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-file
  namespace: compiler
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
