apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: compiler
  labels:
    app: test
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: jenkins:2.60.2
        # image: bitbull/webserver
        ports:
        - containerPort: 80

