

apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    security: s1
spec:
  containers:
  - name: test
    image: supergaintkir/animals:bear
  tolerations:
  - key: "special"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
